### ISSUE TITLE
Ability to add `on_exit` callback for group processes in the same manner as for registry one

### ISSUE THREAD

**Issue by tank-bohr** [ostinelli/syn#10]
I needed this for the use case from README

> Typical Use Case: a chatroom.

To send a system message about user leaving chatroom

**Comment by ostinelli** [comment]
Thank you for the suggestion.

We can add this, but for your specific case you probably have your transport's callback on when a user disconnects, and use that.

**Comment by kwrooijen** [comment]
Would be nice if you could add callbacks for specific groups, instead of adding it to sys.config like you would do for the registry. Just looked through the source and if I'm understanding it correctly, we could simply add a genserver call to add a callback to the group state, and then execute any callbacks on the leave / handle_info flows.

I might be wrong since I just started using this (really liking it), but having this feature would be nice.

**Comment by ostinelli** [comment]
Thank you for your feedback, this can be another enhancement on its own.

**Comment by ostinelli** [comment]
What suggested by @tank-bohr is now implemented. Can you please check?

@kwrooijen, if you're interested can you please open another dedicated issue for this so that we can properly track your request?

**Comment by kwrooijen** [comment]
@ostinelli After re-evaluating my own problem I've figured out a better way to solve it. So I personally don't need this feature. So I'll leave it up to you if you actually think this feature would fit syn or not. Thanks!

**Comment by tank-bohr** [comment]
@ostinelli Thanks a lot for your work! In spite of the fact that I used your advise about transport's callback it could be rather useful feature. And for consistency sane (the group processes now have the same api as registry ones). As my proposal had been implemented entirely I think this issue could be closed. Tanks!
