### ISSUE TITLE
Add a timeout option to multi_call

### ISSUE THREAD

**Issue by essen** [ostinelli/syn#12]
Would be good to have the ability to configure the timeout value for syn:multi_call. For example multi_call/3 with an added Timeout argument. 5000 is a good default but it doesn't fit all use cases.

Additionally it might be worth to monitor to exit early if a crash happened. I think this functionality should try to mirror the gen:call mechanism as much as possible, otherwise it can be dangerous.

**Comment by ostinelli** [comment]
Very nice suggestion. With the moniroting, do you actually suggest to monitor all of the recipient of the multi_call, and add the ones that eventually crash to the list of the `BadPids`?

**Comment by essen** [comment]
Yes. The timeout is great as an upper limit if the process is too busy or locked, but if it crashed or the node is down we definitely want to know sooner, especially for larger timeout values.

**Comment by ostinelli** [comment]
Ok. Unless someone enters a PR for this I will be on it asap.

**Comment by essen** [comment]
I'm not sure my customer will settle on syn yet so that's all the time I can dedicate right now. :-) But I will check again later on. Thanks for considering it.

**Comment by ostinelli** [comment]
@essen, this should conclude the enhancement requested. This implementation:

 * Allows to pass a custom Timeout value.
 * Monitors recipient processes so that if they exit they are immediately added to the list of bad pids.

Let me know if this works for you and I'll package a new Syn.

**Comment by essen** [comment]
Now that you have a reference (the monitor) the next logical thing to do would be to enable the selective receive optimization (when a reference is created in the same function as a receive block that includes said reference in all clauses). But this implies changing the interface for the messages since you need to pass that reference.

Otherwise looks good, and I don't use that function yet in this project so might be a while before I can confirm it works. On the other hand it looks like we'll be using it so thumbs up. :-)

**Comment by ostinelli** [comment]
> Now that you have a reference (the monitor) the next logical thing to do would be to enable the selective receive optimization (when a reference is created in the same function as a receive block that includes said reference in all clauses)

Isn't this what I'm doing?
https://github.com/ostinelli/syn/blob/96904230c33ed618c2969aaecf96d0f3ba2349f0/src/syn_groups.erl#L297

> On the other hand it looks like we'll be using it so thumbs up. :-)

Good to know :)

**Comment by essen** [comment]
You need to do it here also: https://github.com/ostinelli/syn/blob/96904230c33ed618c2969aaecf96d0f3ba2349f0/src/syn_groups.erl#L295

If the process receiving has a large mailbox, having a reference in that message will avoid looking up the whole mailbox every time a message is received.

**Comment by ostinelli** [comment]
Got it.

**Comment by ostinelli** [comment]
Got it, but this is not the case here.

For every recipient, a new process is spawned to send out the call and collect the response. You can see that one process is spawned for every recipient [here](https://github.com/ostinelli/syn/blob/96904230c33ed618c2969aaecf96d0f3ba2349f0/src/syn_groups.erl#L100). These spawned processes are dedicated to receiving the response from only one recipient, so the message box can never grow big: the recipient either responds, it crashes, or this process timeouts.

The real collection of the responses, proxied by the spawned processes, happens [here](https://github.com/ostinelli/syn/blob/96904230c33ed618c2969aaecf96d0f3ba2349f0/src/syn_groups.erl#L310), where the selective receive will match either one of two clauses (so no issue there on the inbox).

The reason why I'm spawning processes to send and collect from one recipient is to ensure the timeout is global and does not get refreshed every time a message is received by the collecting process. Alternatively, I could use `timer:send_after/2` to send a message to self when the timeout has passed, however I don't see any particular benefits of one method over the other (possibly the creation of only one timeout instead of many, but I'd have to see if this really has any kind of real performance impact).

**Comment by essen** [comment]
No it makes sense. Forgot about the spawn. On the other hand the problem exists at https://github.com/ostinelli/syn/blob/96904230c33ed618c2969aaecf96d0f3ba2349f0/src/syn_groups.erl#L310

A bit worried that this receive has no timeout/monitor either, it seems there's an assumption that the multi_call_and_receive process will never die and always send a response back, which is perhaps too optimistic. It's unlikely that it dies (all things considered) but the day it happens we got a process stuck on our hands. (It would most likely survive most normal scenarios, but not a chaos monkey.)

**Comment by ostinelli** [comment]
This is actually managed. :)

As you can see the multi_call_and_receive processes are [spawn_linked](https://github.com/ostinelli/syn/blob/96904230c33ed618c2969aaecf96d0f3ba2349f0/src/syn_groups.erl#L100) to the process that originally requests the multi_call.

So, if one of multi_call_and_receive processes was to die (highly unlikely, but still) then the process that originally requested the multi_call would die too.

Would you like to see a different behaviour?

**Comment by essen** [comment]
Sounds good. I think I need to wake up. :-)

**Comment by ostinelli** [comment]
:) Ok then, looks like I can close this issue.

**Comment by essen** [comment]
Yep, thanks!

**Comment by ostinelli** [comment]
This is now part of syn 1.3.1.
