### ISSUE TITLE
Callback for on process enter

### ISSUE THREAD

**Issue by cjimison** [ostinelli/syn#13]
It would be nice to have a local callback for when a progress has been added to the registry in the same way there is an exit and on conflict.  This way I don't have to poll the group/etc for new membership, etc.

registry_process_enter_callback, [my_callback, callback_on_process_enter]

**Comment by ostinelli** [comment]
Hi @cjimison,
Contrary to exit callbacks, it is actually easy to do what you desire without the additional complication of callbacks.

A process that adds itself just has to publish to the group the fact that it joined, which is way  simpler for me. This is all there's to it:
```erlang
ok = syn:join(my_group, self()),
{ok, _} = syn:publish(my_group, {joined, self()}).
```

**Comment by cjimison** [comment]
Totally.  Just thinking about symmetry of the API is all.

-Chris

**Comment by ostinelli** [comment]
Callbacks for process exits are necessary, simply because there isn't another way to do that (unless you start monitoring processes independently which would be silly since Syn does this already).

On the contrary, callbacks for process enter can easily be solved with alternative solutions, which in my opinion will all be more readable than callbacks in a config file.

Hence, I'll slip this and close this issue for now since it hasn't had any additional traffic / comments since May.

@cjimison thank you again for your feedback :)
