### ISSUE TITLE
Process entry do not cleaned up if register under more then one key.

### ISSUE THREAD

**Issue by vjache** [ostinelli/syn#2]
The i_find_by_pid(...) at.

https://github.com/ostinelli/syn/blob/master/src/syn_backbone.erl#L331

expects a list with only one element which is not correct due to process can be registered more than once, i.e. under several different aliases. As a consequence, such a process will never be cleaned up and table will "leak".

I have tried to solve this issue in an ongoing pull request(just as an illustration), but it is required to change the return type of find_by_pid/1 function to list

**Comment by ostinelli** [comment]
>  process can be registered more than once, i.e. under several different aliases

This is incorrect. If a key already exists, syn will return `{error, taken}`:
https://github.com/ostinelli/syn/blob/master/src/syn_backbone.erl#L114

Why do you think this is not the case?

**Comment by ostinelli** [comment]
This is a good point. Will investigate and provide a patch. Thanks.

**Comment by ostinelli** [comment]
I would actually think not to allow to register a pid under several alias, what do you think?

**Comment by vjache** [comment]
I think it is ok to constrain with registration of only one key per process, at least this keep current API unchanged. But a couple of moments arise:
1) to make check & write atomic, it is required to use transaction, which makes registration not so fast. An alternative is to use additional gen_server for registration of local pids.
2) also what if the same pid tried to be registered with the same key more than once? Keep silence? Raise error? Or return something like 'already_registered'? I would choose the last one.

**Comment by ostinelli** [comment]
Hi, thank you for raising this. Commit ad53b6e20f499e9cf0d5ee005f6f6fd867653e13 tackles this with the following choices:

 * Ensure atomicity at node level (still without using a mnesia transaction). This is achieved by making all the registrations happens inside the `syn_backbone` gen_server process. This means that all registrations on one node are forcefully sequential. Of course, this doesn't guarantee for atomicity across the cluster, but that's why we have `syn_consistency`.
 * If a Pid is being registered twice, then the new error `pid_already_registered` [is raised](https://github.com/ostinelli/syn/blob/0.8.0/src/syn_backbone.erl#L185).

I'm closing your pull request in favor of this one.

Thank you for your input!
