### ISSUE TITLE
Which OTP versions are supported?

### ISSUE THREAD

**Issue by dcsommer** [ostinelli/syn#28]
I didn't see a description anywhere which versions are supported. I would assume R18 since that was around the time this was written, but I am also curious about R19.

**Comment by ostinelli** [comment]
Take a look at [.travis.yml](https://github.com/ostinelli/syn/blob/master/.travis.yml).

I haven't added R19 yet simply because I don't know if it's currently supported by Travis. I haven't found any official docs on which versions are supported, if you have any idea where to find that list - it sould be appreciated ^^_

**Comment by ostinelli** [comment]
I've updated the list of Travis builds yesterday, supported up to 19.1:
https://travis-ci.org/ostinelli/syn
