### ISSUE TITLE
Not able to receive messages to a process group after node split rejoin

### ISSUE THREAD

**Issue by jeremytregunna** [ostinelli/syn#30]
I've got two nodes, A and B which service users who can communicate with one another. In the event A splits from B, and later rejoins, A no longer receives messages originated from B. Since I can't call `syn.init()` again, how do I correct this behavior?

**Comment by ostinelli** [comment]
You shouldn't do anything, Syn will perform [the merge](https://github.com/ostinelli/syn/blob/1.6.0/src/syn_consistency.erl#L123) for you automatically after node B rejoins.

Are you sure the two nodes reconnected? Erlang alone won't do this since it does not manage reconnection. For instance in production systems I use Syn in conjunction with [Cowbell](https://github.com/ostinelli/cowbell).

**Comment by jeremytregunna** [comment]
Yeah I'm reconnecting for sure. Project is actually an Elixir project, and I'm running this through iex. So I'm manually issuing a `Node.connect :"app@1.2.3.4"` and checking `Node.list` after.

**Comment by ostinelli** [comment]
@jeremytregunna I don't know what you are experiencing. There currently is a [test suite](https://github.com/ostinelli/syn/blob/1.6.0/test/syn_groups_consistency_SUITE.erl) that covers this, on top of actually having seen it amend in production environments myself more than once.

Care to show me how to reproduce? Erlang only though.

**Comment by jeremytregunna** [comment]
I've not been able to reproduce after building a small test. Clearly there's an issue with my main app. Thank you. Closing.
