### ISSUE TITLE
callbacks improvements

### ISSUE THREAD

**Issue by silviucpp** [ostinelli/syn#60]
Can you add also callbacks when a process join a group or a new pid is registered ? Right now I see callbacks are only when a pid leaves a group...

Silviu

**Comment by ostinelli** [comment]
I don't really see a benefit in this, since contrary to a process leaving a group / unregistering (where it may have crashed), you're in control when you register a process / join a group. Basically, in the same method where you register a new pid / join a group you can call whatever it is that you need to call beforehand.

Do you have a specific case where you'd need such a callback?

**Comment by silviucpp** [comment]
Hello, yes during a  between node A and B I receive that the processes on
the other node left the group and when connection goes back you merge the
states but in the app I don’t know that the processes are back . I eve
don’t know when merge was performed to call syn and see what processes are
in that group.

Having a callback called when the merge was completed and also when a
process joins the group (or at least one of those) allows the apps to
better handle this kind of “presence”.

Silviu
